"""
运行态后端接口。
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class RuntimeStateBackend(Protocol):
    def init_schema(self) -> None: ...

    def get_schema_version(self) -> int: ...

    def validate_integrity(self) -> bool: ...

    def get_thread_id(self, user_id: int) -> str | None: ...

    def set_thread_id(self, user_id: int, thread_id: str) -> None: ...

    def save_foreground_operation(self, operation) -> None: ...

    def load_foreground_operations(self) -> list: ...

    def delete_foreground_operation(self, user_id: int | str) -> None: ...

    def save_blob(self, key: str, value: bytes) -> None: ...

    def load_blob(self, key: str) -> bytes | None: ...

    def delete_blob(self, key: str) -> None: ...

    def list_blob_keys(self, prefix: str = "") -> list[str]: ...
